server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/appbox
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: true
